---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: Cloud Infrastructure
  children:
  - name: XL Deploy
    type: xldeploy.XLDeployServer
    url: http://localhost:4599
    username: admin
    password: admin
  - name: Service Now
    type: servicenow.Server
    url: https://dev86267.service-now.com
    username: admin
    password: wdq7iLPhHG
    useServicenowApp: false        
- directory: PetPortal
  children:
  - name: XL Deploy
    type: xldeploy.XLDeployServer
    url: http://localhost:4599
    username: admin
    password: admin
