---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/terraform-host
  type: overthere.LocalHost
  os: UNIX
- name: Infrastructure/terraform-cloud
  type: terraformEnterprise.Organization
  organizationName: xebialabs-france
  url: https://app.terraform.io
  token: !value "tfe_token"   
  deleteWorkspace: true
  host: Infrastructure/terraform-host
  children:
  - name: aws
    type: terraformEnterprise.AwsProvider
    accessSecret: !value "aws_secret_access_key"
    accessKey: !value "aws_access_key_id"
    defaultRegion: "eu-west-3"
  - name: azure-xl
    type: terraformEnterprise.AzureProvider
    subscriptionId: !value "subscriptionId"
    tenantId: !value "tenantId"
    clientId: !value "clientId"
    clientKey: !value "clientKey"
