---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/ansible-host
  type: overthere.LocalHost
  os: UNIX
  children:
    - name: defaultAnsibleController
      type: ansible.Controller
      devopsAsCodeUrl: http://localhost:4599
      devopsAsCodeDirectory: /tmp/webinar-infra

